export type ExportFormat = 'markdown' | 'html' | 'pdf';

/**
 * Convert Markdown to HTML with basic styling
 */
function markdownToHtml(markdown: string): string {
  let html = markdown
    // Headers
    .replace(/^### (.*$)/gim, '<h3>$1</h3>')
    .replace(/^## (.*$)/gim, '<h2>$1</h2>')
    .replace(/^# (.*$)/gim, '<h1>$1</h1>')
    // Bold and italic
    .replace(/\*\*(.*?)\*\*/gim, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/gim, '<em>$1</em>')
    // Lists
    .replace(/^\- (.*$)/gim, '<li>$1</li>')
    .replace(/(<li>.*<\/li>)/gims, '<ul>$1</ul>')
    // Code blocks
    .replace(/```([\s\S]*?)```/gim, '<pre><code>$1</code></pre>')
    // Inline code
    .replace(/`([^`]+)`/gim, '<code class="inline-code">$1</code>')
    // Line breaks
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br>');

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Analysis Report</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
      line-height: 1.6;
      color: #1e293b;
      max-width: 800px;
      margin: 40px auto;
      padding: 20px;
      background: #f8fafc;
    }
    h1, h2, h3 {
      color: #0f172a;
      margin-top: 1.5em;
      margin-bottom: 0.5em;
    }
    h1 { font-size: 2em; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.3em; }
    h2 { font-size: 1.5em; border-bottom: 1px solid #e2e8f0; padding-bottom: 0.3em; }
    h3 { font-size: 1.25em; }
    p { margin-bottom: 1em; }
    ul { margin-bottom: 1em; padding-left: 1.5em; }
    li { margin-bottom: 0.25em; }
    pre {
      background: #1e293b;
      color: #e2e8f0;
      padding: 1em;
      border-radius: 0.5em;
      overflow-x: auto;
      margin-bottom: 1em;
    }
    code {
      font-family: 'Monaco', 'Courier New', monospace;
      font-size: 0.9em;
    }
    .inline-code {
      background: #e2e8f0;
      padding: 0.2em 0.4em;
      border-radius: 0.25em;
      font-size: 0.9em;
    }
    .header {
      text-align: center;
      margin-bottom: 2em;
      padding-bottom: 1em;
      border-bottom: 2px solid #3b82f6;
    }
    .header h1 {
      border: none;
      margin: 0;
      color: #3b82f6;
    }
    .footer {
      margin-top: 3em;
      padding-top: 1em;
      border-top: 1px solid #e2e8f0;
      text-align: center;
      color: #64748b;
      font-size: 0.875em;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>CellMind Analysis Report</h1>
    <p>Generated on ${new Date().toLocaleString()}</p>
  </div>
  <div class="content">
    <p>${html}</p>
  </div>
  <div class="footer">
    <p>Generated by CellMind - Single-Cell Analysis Platform</p>
  </div>
</body>
</html>
  `;
}

/**
 * Download content as a file
 */
function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export report in the specified format
 */
export function exportReport(content: string, title: string, format: ExportFormat): void {
  const sanitizedTitle = title.replace(/[^a-z0-9]/gi, '_').toLowerCase().slice(0, 50);
  const timestamp = new Date().toISOString().slice(0, 10);

  switch (format) {
    case 'markdown':
      downloadFile(content, `${sanitizedTitle}_${timestamp}.md`, 'text/markdown');
      break;

    case 'html':
      const html = markdownToHtml(content);
      downloadFile(html, `${sanitizedTitle}_${timestamp}.html`, 'text/html');
      break;

    case 'pdf':
      // For PDF, we'll use the browser's print functionality
      // Create a new window with the HTML content
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(markdownToHtml(content));
        printWindow.document.close();
        // Wait for content to load, then print
        setTimeout(() => {
          printWindow.print();
        }, 250);
      }
      break;

    default:
      console.error(`Unsupported export format: ${format}`);
  }
}

/**
 * Get file extension for export format
 */
export function getFormatExtension(format: ExportFormat): string {
  switch (format) {
    case 'markdown': return '.md';
    case 'html': return '.html';
    case 'pdf': return '.pdf';
    default: return '';
  }
}
